### ISSUE TITLE
How to clear/delete xdns_a_records map

### ISSUE THREAD

**Issue by ChenYahui2019** [zebaz/xpress-dns#2]
I'd like to ask you just one question:
how to delete xdns_a_records map?

**Comment by ChenYahui2019** [comment]
The commond `rm /sys/fs/bpf/xdp/globals/xdns_a_records` can delete the map.

**Comment by zebaz** [comment]
You are correct that you can delete the map by removing it from the pseudo filesystem as you've mentioned in your comment :).
I chose to use map pinning (PIN_GLOBAL_NS) so that the xdns_a_records map persists across load/unload of XDP objects, and so it can be shared across multiple interfaces.
